"""empty message

Revision ID: 2c324fc3a342
Revises: 112be7cdca0c
Create Date: 2024-06-19 11:11:31.978896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c324fc3a342'
down_revision = '112be7cdca0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outlines', sa.Text(), nullable=True))
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', mysql.TEXT(), nullable=True))
        batch_op.drop_column('outlines')

    # ### end Alembic commands ###
