"""empty message

Revision ID: 3e0fedc09ff1
Revises: dd8d578147fa
Create Date: 2024-07-08 10:41:16.149538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0fedc09ff1'
down_revision = 'dd8d578147fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'contents', ['content_id'], ['id'])

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_column('llm')

    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('content_id')

    # ### end Alembic commands ###
