"""empty message

Revision ID: 525e01940370
Revises: 2c324fc3a342
Create Date: 2024-06-19 21:31:15.088973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '525e01940370'
down_revision = '2c324fc3a342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=postgresql.TEXT(),
               type_=postgresql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=postgresql.TEXT(),
               type_=postgresql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
