"""empty message

Revision ID: 86282f96e17a
Revises: c0ed25c37f76
Create Date: 2024-06-21 17:55:39.055047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86282f96e17a'
down_revision = 'c0ed25c37f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_column('word_count')

    # ### end Alembic commands ###
