"""empty message

Revision ID: c0ed25c37f76
Revises: 525e01940370
Create Date: 2024-06-20 21:16:45.041696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0ed25c37f76'
down_revision = '525e01940370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mongo_id', sa.String(length=24), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_column('mongo_id')

    # ### end Alembic commands ###
