version: '3.8'

services:
  web:
    build: .
    entrypoint: scripts/webapp_ep.sh
    restart: always
    volumes:
      - .:/app
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
      - mysql
    networks:
      - backend
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  worker:
    build: .
    restart: always
    entrypoint: scripts/celery_ep.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
      - mysql
    networks:
      - backend
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8082
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_ADMIN}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
      - ME_CONFIG_BASICAUTH=false
    networks:
      - backend

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - backend

volumes:
  mongo-data:
  mysql-data:

networks:
  backend:
    driver: bridge