version: '3.8'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=80
    volumes:
      - .:/app
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
      - mysql

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123qwer
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123qwer
      ME_CONFIG_MONGODB_URL: mongodb://admin:123qwer@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123qwer
      MYSQL_DATABASE: app
      MYSQL_PASSWORD: 123qwer
    ports:
      - "3306:3306"

volumes:
  mongo-data:
  mysql-data: