version: '3.8'

services:
  web:
    build: .
    entrypoint: scripts/webapp_ep.sh
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
      - mysql
    networks:
      - backend
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.papkorn-app.rule=Host(`behnevis.tosihgar.ir`)"
      - "traefik.http.routers.papkorn-app.entrypoints=websecure"
      - "traefik.http.routers.papkorn-app.tls.certresolver=myresolver"

  worker:
    build: .
    restart: always
    entrypoint: scripts/celery_ep.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
      - mysql
    networks:
      - backend
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_ADMIN}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
      - ME_CONFIG_BASICAUTH=false
    networks:
      - backend

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`nh-mongoexpress.tosiehgar.ir`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.routers.whoami.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=papkorn:$$2y$$05$$x2eP45dysR1z7CaZNZcxfujdtkk3gbHZzhvwCM73IgxaTRdTWuo4i"

  redis:
    image: redis:alpine
    restart: always
    networks:
      - backend

  mysql:
    image: mariadb:11.4.2
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - backend

volumes:
  mongo-data:
  mysql-data:

networks:
  backend:
    external: True